### ISSUE TITLE
Crashes during drafting of reply

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/android#399] opened 2021-07-26 02:37 UTC
### Environment

Pixel 4a running CalyxOS, Android 11.
F-droid Mobile App v1.5.0

### Steps to reproduce

1. Received email from ProtonMail address.
2. Clicked reply at the bottom of app screen.
3. Near immediate crash of app. Message was saved in Drafts.
4. Re-entered app, entered Drafts, clicked on saved draft to construct reply.
5. Immediate crash.

### Expected behavior

Allow me to construct reply email.

### Actual behavior

Instant and repeated crashes.
Including (low quality lol) screen recording below.

https://user-images.githubusercontent.com/74485231/126925409-8acd2ca3-b101-40db-9f4f-cb0e1b86d30d.mp4

**Comment by alexdwork2018** [comment] 2021-08-04 20:28
Hello @SecretestSquirrel ! Unfortunately, I was unable to repeat the issue you described. Perhaps there were some unusual characters in the received letter, or was it formed with additional parameters?
You can also enable the Report bugs in the app settings, restart the app and repeat steps to reproduce this issue on your device. This will help us to analyze which errors in the code lead to this issue.

**Comment by SecretestSquirrel** [comment] 2021-08-08 07:19
Yeah, I have force stopped, then when ahead and completely uninstalled/reinstalled, I cannot even begin to draft an email or response whatsoever. As soon as I tap the compose button it takes me to the email composition page, then within 2 seconds crashes completely and all I'm left with is a floating notification at the bottom of the screen letting me know it had been saved as a draft. This is on reply or compose direct.

Honestly have no idea what to do, the app is completely unusable for me, again on Pixel 4a running CalyxOS v2.8.0, Android 11. The web version works perfectly fine, so I am able to do what I need to do from there, but I am really at a loss as to how I can help try to fix this issue in the F-droid app v1.5.0.

**Comment by alexdwork2018** [comment] 2021-08-12 18:16
hi @SecretestSquirrel . You can help find the cause of the error. If you can, please activate the bug reports feature in the app settings as I described above, and then repeat the steps for reproducing the issue on your device.

**Comment by xxxcrow** [comment] 2021-08-20 23:58
having the same issue 👋
xiaomi mi 9
android 11 (aosp)

**Comment by xxxcrow** [comment] 2021-08-21 00:25
not sure if it can be related
I changed a lot of settings before this started to happen
and also I replaced my pgp keys (and also lost all my emails 😂)
and now also:
my contacts crush
turning off contacts decryption is not working

**Comment by SecretestSquirrel** [comment] 2021-08-23 22:09
> hi @SecretestSquirrel . You can help find the cause of the error. If you can, please activate the bug reports feature in the app settings 

I have done this, and created a couple more crashes. Note, these are on the newest version of the app now, v1.5.1, rather than the original v1.5.0 the original report was about. It actually seems to have gotten a little worse now, as I cannot even begin to simply compose a message, not just a reply.

https://user-images.githubusercontent.com/74485231/130525790-56bfbe73-86cf-47de-a569-b50835e24493.mp4

**Comment by The-Hidden-Hand** [comment] 2021-08-24 11:02
@alexdwork2018
Did you get the error's traceback to debug?

**Comment by alexdwork2018** [comment] 2021-09-01 19:27
@SecretestSquirrel thanks for the help with the bug report.
Noticed this issue in one more another user. In fact, the reason is broken encrypted contacts, decoding of which leads to an error. And since contacts are used in compose tips, this led to an error.

@all If someone manages to repeat the flow to break contacts in one of the clients, please let us know.

The new app version with error handling for this and other issues have already been published in the new release and will be available as soon as the app stores will publish them.

**Comment by xxxcrow** [comment] 2021-09-01 19:54
@alexdwork2018 repeat the workflow on old version or new?

**Comment by alexdwork2018** [comment] 2021-09-02 09:35
@xxxcrow In the new version. The new version now handles broken contacts that cannot be decrypted. But the ability to break contacts is still there, be it an unusual flow with generating and removing additional keys in mailboxes or intentional user actions. It will be fixed when enough details will be collected about this issue.

**Closed by alexdwork2018** 2021-09-02 09:35 UTC
Labels: bug
